### ISSUE TITLE
RP2040 ISA

### ISSUE THREAD

**Issue by jonathanpallant** [UPB-FILS-MA/upb-fils-ma.github.io#111]
https://github.com/UPB-FILS-MA/upb-fils-ma.github.io/blob/main/slides/lectures/01/rp2040/slides.md describes the ISA of the Cortex-M0+ as being `thumbv-1 (armv6-m)`.

I think the architecture is more accurately described as `[Armv6-M](https://developer.arm.com/documentation/ddi0419/e/?lang=en)`, a processor architecture which executes a subset of what is now called the [T32 Instruction Set Architecture](https://developer.arm.com/Architectures/T32%20Instruction%20Set%20Architecture). Specifically, the subset supported by Armv6-M includes the old Thumb ISA, *and* parts of the old Thumb-2 ISA.

Arm continue to prove that the hardest problem in computer science is naming things.

**Comment by alexandruradovici** [comment]
Thank you for the feedback, I'll submit a PR to fix this.
