### ISSUE TITLE
I2C

### ISSUE THREAD

**Issue by jonathanpallant** [UPB-FILS-MA/upb-fils-ma.github.io#112]
> IntraIntegrated Communication TODO

It's the *Inter-IC Bus*, where *IC* is *Integrated Circuit*.

**Comment by alexandruradovici** [comment]
Do we have a TODO with this in the slides?

**Comment by jonathanpallant** [comment]
yeah ;)

**Comment by jonathanpallant** [comment]
![image](https://github.com/UPB-FILS-MA/upb-fils-ma.github.io/assets/18005923/9b50cc3a-0457-40c0-b693-8237be4230d0)
