### ISSUE TITLE
Embassy setup

### ISSUE THREAD

**Issue by DTeodor-Alexaandru** [UPB-FILS-MA/upb-fils-ma.github.io#27]
We need to make an embassy setup tutorial for students.
This needs to cover all prerequisites needed and a step by step tutorial of how to program the MCU and how to use the debugger.
It should cover every OS and an alternitive if there might be problems.

**Deadline**: 10.03 (last weekend before the first MCU lab)

**Comment by alexandruradovici** [comment]
What about putting this tutorial in the first MCU lab?

**Comment by DTeodor-Alexaandru** [comment]
I would put it separately because I wanted to publish before the first MCU lab for them to have enough time to do the setup and for us to help them if needed.

**Comment by alexandruradovici** [comment]
I see your point. Are referring to the instalation of rust and the additional tools, like probe rs, gdb and vscode?

I suggest having a tutorials section where we add this and a similar turorial for KiCad.

**Comment by DTeodor-Alexaandru** [comment]
Yess, I will take care of the Kicad tutorial.
