### ISSUE TITLE
Lecture 09 display issues

### ISSUE THREAD

**Issue by VladVulturescu** [UPB-FILS-MA/upb-fils-ma.github.io#290]
While reading lecture 9 I noticed some graphical and display issues.

1) On slide 6, some of the text is missing (the last line - "permissions R W X")

<img width="1440" alt="MA - Lecture 09 - Display Issue - slide 6" src="https://github.com/UPB-FILS-MA/upb-fils-ma.github.io/assets/105521724/ef5628d5-eecd-42d4-8aaf-6267bda7d47e">

When using Safari, you can see a little bit of the upper part of the text but on Chrome and Firefox "permissions R W X" doesn't appear at all

<img width="1440" alt="MA - Lecture 09 - Display Issue on Chrome - slide 6" src="https://github.com/UPB-FILS-MA/upb-fils-ma.github.io/assets/105521724/fb0dc3dc-cb24-4c5a-b49a-fdb95519411e">

2) On slides 19 and 20, while reading the course in dark mode, the diagrams are very faded and difficult to understand

<img width="1440" alt="MA - Lecture 09 - Display Issue - slide 19" src="https://github.com/UPB-FILS-MA/upb-fils-ma.github.io/assets/105521724/ae8d134a-cde6-4942-83fa-944460c48fa0">

<img width="1440" alt="MA - Lecture 09 - Display Issue - slide 20" src="https://github.com/UPB-FILS-MA/upb-fils-ma.github.io/assets/105521724/0122c064-ba54-493d-bd5b-306852bcd8df">

3) When changing from slide 20 to slide 21 or from slide 22 back to slide 21, the microcontroller and microprocessor images do not display properly. This only happens when you change slides after a few seconds. The images will display correctly if you switch between the slides very fast.

<img width="1440" alt="MA - Lecture 09 - Display issue - slide 21" src="https://github.com/UPB-FILS-MA/upb-fils-ma.github.io/assets/105521724/2d723ede-1edd-4d90-bace-bc7e5c3e120f">

This might be a problem only on Safari, since I wasn't able to replicate this on Chrome

**Comment by alexandruradovici** [comment]
Thank you for the feedback, we tried to temporary fix them by adding a white background. We will improve the slides for dark mode later.

The images problem is most probably a browser issue.
