### ISSUE TITLE
LAB4 duplicate exercise 

### ISSUE THREAD

**Issue by domnudragota** [UPB-FILS-MA/upb-fils-ma.github.io#79]
Do we do this exercise twice ??
![image](https://github.com/UPB-FILS-MA/upb-fils-ma.github.io/assets/130050495/8781d2eb-90ea-4c65-816b-60ad376757f8)

**Comment by UdrAlberto** [comment]
Also, we have 2 exercises 4 (first and last row of my screenshot)

![image](https://github.com/UPB-FILS-MA/upb-fils-ma.github.io/assets/94986973/ce515f43-1b01-400c-8bb5-f012be034542)

**Comment by UdrAlberto** [comment]
#80
